### ISSUE TITLE
Create a ToDo-list

### ISSUE THREAD

**Issue by cyvu** [cyvu/html-css#18]
- Difficulty 3/10

- Create new branch: todo

We need a mock of a "to do"-list

- [x] It should be self-containing in a new section. Placed ideally within the third article.

- [x] Each row within the "to do"-list should have a checkbox
- [x] an empty row for the text (optionally containing a placeholder text)
- [x] a row for date_add
- [x] a row for date_checked

- [x] Give it at least 5 visible rows
